import Vue from 'vue';
import {FontAwesomeIcon} from '@fortawesome/vue-fontawesome';
import {library} from '@fortawesome/fontawesome-svg-core';
import {
    faAddressCard,
    faArrowCircleRight,
    faArrowDown,
    faArrowUp,
    faBan,
    faBookOpen,
    faCalendarDay,
    faCaretDown,
    faCheck,
    faChevronLeft,
    faChevronRight,
    faChevronUp,
    faEdit,
    faEnvelope,
    faEye,
    faEyeSlash,
    faFilePdf,
    faMapMarker,
    faMicrophone,
    faNewspaper,
    faPhone,
    faPhoneAlt,
    faPhotoVideo,
    faPlus,
    faShareAlt,
    faSpinner,
    faTimes,
    faTrash,
    faSearch,
    faUser,
    faVideo,
} from '@fortawesome/free-solid-svg-icons';

import {
    faFacebookF,
    faFacebookSquare,
    faInstagram,
    faLinkedinIn,
    faLinkedin,
    faTwitter,
    faTwitterSquare,
    faYoutube,
    faYoutubeSquare,
} from '@fortawesome/free-brands-svg-icons';

library.add(
    faAddressCard,
    faArrowCircleRight,
    faArrowDown,
    faArrowUp,
    faBan,
    faBookOpen,
    faCalendarDay,
    faCaretDown,
    faCheck,
    faChevronLeft,
    faChevronRight,
    faChevronUp,
    faEye,
    faEyeSlash,
    faEdit,
    faEnvelope,
    faFacebookF,
    faFacebookSquare,
    faFilePdf,
    faInstagram,
    faLinkedinIn,
    faLinkedin,
    faMapMarker,
    faMicrophone,
    faNewspaper,
    faPhone,
    faPhoneAlt,
    faPhotoVideo,
    faPlus,
    faSearch,
    faShareAlt,
    faSpinner,
    faTrash,
    faTimes,
    faTwitter,
    faTwitterSquare,
    faUser,
    faVideo,
    faYoutube,
    faYoutubeSquare,
);

Vue.component('fa', FontAwesomeIcon);
